; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Aug 27 2020 15:36:37 GMT-0400 (Eastern Daylight Time)

;G10 P1 R210			; override standby temp
;G1 X252 F12000		; move to purge position
;M83					; relative extrusion
;G1 E4 F420			; ram
;G1 E-27 F420		; retract