; tpre1.g
; called before tool 1 is selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Aug 27 2020 15:36:37 GMT-0400 (Eastern Daylight Time)

;M83				;relative extrusion
				;wiping old filament
;G1 X252 F1200
;G1 X225 F1200
;G1 X252 F1200